name: 'Bit Branch Lane'
description: 'Create a new Bit lane for each new Git branch'
branding: 
  icon: 'git-branch'
  color: 'purple'
inputs:
  ws-dir:
    description: "Workspace json file directory path"
    required: false
  lane:
    description: "The source Bit lane name where the updates are fetched from"
    required: false
  skip-push:
    description: "Skip commit push (for testing)"
    required: false
runs:
  using: 'node20'
  main: 'dist/index.js'
