name: 'Bit Lane Branch'
description: 'Create a new Bit lane for each new Git branch'
branding: 
  icon: 'git-merge'
  color: 'purple'
inputs:
  ws-dir:
    description: "Workspace json file directory path"
    required: false
  lane-name:
    description: "The name of the Bit lane to sync from in the format: org.scope/lane"
    required: true
  branch-name:
    description: "The destination Git branch name where the updates are sync to"
    required: false
  skip-push:
    description: "Skip commit push (for testing)"
    required: false
  skip-ci:
    description: "Remove adding [skip-ci] to the .bitmap file commit message"
    required: false
runs:
  using: 'node20'
  main: 'dist/index.js'
