name: Test Bit Lane Branch
on:
  workflow_dispatch:
    inputs:
      lane:
        description: 'The name of the lane to sync from'
        required: true
        default: 'main'
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GIT_USER_NAME: ${{ secrets.GIT_USER_NAME }}
      GIT_USER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
      BIT_CONFIG_ACCESS_TOKEN: ${{ secrets.BIT_CONFIG_ACCESS_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Initialize Bit
        uses: bit-tasks/init@v2
        with:
          ws-dir: 'test-data'
      - name: Creating a bare scope
        run: mkdir org.scope-name && cd org.scope-name && bit init --bare
      - name: Start the server and test
        run: cd org.scope-name && bit start --port 4000 --no-browser & sleep 200 && curl http://localhost:4000 
      - name: Add remote scope
        run: cd test-data && bit remote add http://localhost:4000
      - name: Snap and export
        run: cd test-data && bit lane create "${{ github.event.inputs.lane }}" && bit snap -m "Snapping the changes" && bit export
      - name: Import the lane
        uses: bit-tasks/init@v2
        with:
          ws-dir: 'test-data'
          lane: ${{ github.event.inputs.lane }}
      - name: Bit Lane Branch
        uses: bit-tasks/lane-branch@main
        with:
            branch-name: 'main'
            skip-push: 'true'
      - name: Bit Lanes
        run: cd test-data && bit lane list --details
          