name: Test Bit Lane Branch
on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GIT_USER_NAME: ${{ secrets.GIT_USER_NAME }}
      GIT_USER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
      BIT_CONFIG_ACCESS_TOKEN: ${{ secrets.BIT_CONFIG_ACCESS_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Initialize Bit
        uses: bit-tasks/init@v1
        with:
            ws-dir: 'test-data'
      - name: Creating a bare scope
        run: mkdir org.scope-name && cd org.scope-name && bit init --bare
      - name: Start the server and test
        run: cd org.scope-name && bit start --port 4000 --no-browser & sleep 200 && curl http://localhost:4000 
      - name: Add remote scope
        run: cd test-data && bit remote add http://localhost:4000
      - name: Create lane to test
        run: cd test-data && bit lane create "test-lane"
      - name: Snap and export
        run: cd test-data && bit snap -m "Snapping the changes" && bit export -m "Exporting the changes"
      - name: Bit Lane Branch
        uses: bit-tasks/lane-branch@main
        with:
            lane: 'test-lane'
            skip-push: 'true'
      - name: Bit Lanes
        run: cd test-data && bit lane list --details
          